#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
Hour=0
while [ $Hour -le 12 ]
do
	echo "Hour: $Hour"
	M=1
	while [ $M -le 59 ]
	do
		echo $M
		((M++))
	done
	((Hour++))
done
